# Generated by Django 4.2.5 on 2024-02-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('matric_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Stud',
            },
        ),
    ]
