# Generated by Django 4.2.5 on 2024-05-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_note_author_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='note',
        ),
    ]
