# Generated by Django 4.2.5 on 2024-10-28 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_achievements_profile_bio_profile_career_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade_points',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
