# Generated by Django 4.2.5 on 2024-10-28 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_grade_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
